In [1]:
import scanpy as sc
import pandas as pd
import numpy as np

In [2]:
adata = sc.datasets.pbmc68k_reduced()

In [3]:
adata

AnnData object with n_obs × n_vars = 700 × 765
    obs: 'bulk_labels', 'n_genes', 'percent_mito', 'n_counts', 'S_score', 'G2M_score', 'phase', 'louvain'
    var: 'n_counts', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'
    uns: 'bulk_labels_colors', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'
    layers: None (.X)

In [4]:
adata.obs["bulk_labels"].value_counts()

bulk_labels
Dendritic                       240
CD14+ Monocyte                  129
CD19+ B                          95
CD4+/CD25 T Reg                  68
CD8+ Cytotoxic T                 54
CD8+/CD45RA+ Naive Cytotoxic     43
CD56+ NK                         31
CD4+/CD45RO+ Memory              19
CD34+                            13
CD4+/CD45RA+/CD25- Naive T        8
Name: count, dtype: int64

In [5]:
adata.obs[["bulk_labels"]].head()

                      bulk_labels
index
AAAGCCTGGCTAAC-1   CD14+ Monocyte
AAATTCGATGCACA-1        Dendritic
AACACGTGGTCTTT-1         CD56+ NK
AAGTGCACGTGCTA-1  CD4+/CD25 T Reg
ACACGAACGGAGTG-1        Dendritic

In [6]:
adata.X.shape

(700, 765)

In [7]:
adata.var.head()

            n_counts     means  dispersions  dispersions_norm  highly_variable
index
HES4     1153.387451  0.592365     2.028047          2.771764             True
TNFRSF4   304.358154  0.193332     1.760724          2.746426             True
SSU72    2530.272705  1.019981     1.208284         -0.631160            False
PARK7    7451.664062  1.828078     1.288261         -0.544716            False
RBP7      272.811035  0.174943     1.842789          3.192285             True

In [10]:
from pathlib import Path

In [11]:
Path.cwd()

PosixPath('/Users/Tommy/Documents/GitHub/ImmunoType/notebooks')

In [12]:
adata.write("../data/raw/pbmc68k_reduced/pbmc68k_reduced.h5ad")

In [13]:
path = Path("../data/raw/pbmc68k_reduced/pbmc68k_reduced.h5ad")

In [14]:
print(path.resolve())
print(path.exists())

/Users/Tommy/Documents/GitHub/ImmunoType/data/raw/pbmc68k_reduced/pbmc68k_reduced.h5ad
True